### ISSUE TITLE
Document-level views ⚖104

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#100]
There is a visualisation for the dates that individual students have accessed the page. What would be really useful is a visualisation of which students have accessed certain documents/videos/activities rather than just the date (as they might log onto Moodle, look at the work uploaded and click back off without accessing the document needed).

**Comment by robbristow-jisc** [comment]
Can't see how to find this visualisation - can someone give me a clue?

**Comment by leebaylis** [comment]
think it's site explorer, all modules, view one, change to VLE content use and then click a bar

**Comment by robbristow-jisc** [comment]
That looks ok - when I follow Lee's script, I can go Site Explorer -> All Module -> View -> Change to VLE Content use and then a particular and then see the name of the student and a horizontal bar showing their activity
<img width="981" alt="screen shot 2017-08-04 at 09 27 07" src="https://user-images.githubusercontent.com/30286590/28960570-1fe86ac0-78f7-11e7-874b-fb0f6bdfc9ba.png">

**Comment by robbristow-jisc** [comment]
mant to add that that works both on Staging and Dev
