### ISSUE TITLE
module view -- break down vle use by item ⚖104

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#101]
Really useful being able to click on items within VLE content to view which students have consumed

**Comment by robbristow-jisc** [comment]
Is this the same as 104?

**Comment by leebaylis** [comment]
oh -- maybe what I wrote for 100 was for this instead!
OK, I am confused now -- I thought one of these was for click on a student and see what they have consumed, and the other one was for click the content and see which students have consumed it.

**Comment by leebaylis** [comment]
duplicate of #100
