### ISSUE TITLE
Show results of LAP ⚖80

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#103]
I've added this one in after discussion option to show as speedo.

**Comment by michaelwebbjisc** [comment]
Quick update: inital build passed to dev server.  Still to do:

![image](https://user-images.githubusercontent.com/8233360/27220148-0e6692c8-527c-11e7-8fe9-91ba910eddff.png)
Add Comment

paul.bailey [10:07 AM] 

For the module with 50% Pass Prob. So expect to see same dial here as on main screen.  Also change text to say Pass Probability.

**Comment by robbristow-jisc** [comment]
Does this need testing?

**Comment by robbristow-jisc** [comment]
Still can't see what I am testing - Is there a way of getting to the Latest risk predictions? If so, I can't see it

**Comment by leebaylis** [comment]
Hi Rob, 

Should be implemented for Gloucester Live on staging -- spot test with a few students by going to all students, clicking view on them and then clicking a few of their modules.

**Comment by robbristow-jisc** [comment]
Assuming that I am looking at the right thing, what I see on Uni Gloucester Love on Staging is a nice dial with a percentage and (so far only) Green traffic lights for online and achievement. See screen shot. 

<img width="1303" alt="screen shot 2017-08-11 at 15 00 24" src="https://user-images.githubusercontent.com/30286590/29216315-31720882-7ea6-11e7-8eec-557c28a19b83.png">

Is this what you expect?

Not all modules have a dial - some just the traffic lights. Again, is this what you are expecting?

**Comment by leebaylis** [comment]
I think so, although probably worth us checking which don't have the dials and why... do you have example of one without?

**Comment by leebaylis** [comment]
18/8 call: none of us are sure when we are supposed to see dials, when lights and when nothing, and where the data comes from -- @michaelwebbjisc can you help?
