### ISSUE TITLE
 Module title hidden by graph

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#104]
Module heading elements aren’t long enough – even short strings partially cover over the graph type selection box. can we implement line wrapping, or is there any other way we can avoid the graph type box being obscured?

![image](https://cloud.githubusercontent.com/assets/1846710/26784221/5de1065c-49f4-11e7-94d9-0a9ccffd96eb.png)

from https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/53

**Comment by leebaylis** [comment]
Submitted by Gloucester

**Comment by michaelwebbjisc** [comment]
This has also been submitted by USW: https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/250

**Comment by robbristow-jisc** [comment]
Not sure of the status of this - is it ready for testing?

**Comment by robbristow-jisc** [comment]
The Graph Type drop down now does not pop up and obscure the Module overview as in the screenshot of 5th June. However it does drop down over the title of the visualisation and obscures it. 
<img width="735" alt="screen shot 2017-08-04 at 09 54 29" src="https://user-images.githubusercontent.com/30286590/28961761-639115ca-78fb-11e7-999c-9c48915964af.png">
