### ISSUE TITLE
USW shows no viz when selecting student > assessment over time

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#107]
Have spot checked against several students. 

This is the specific bug to fix this for gloucester data -- there is another issue relating to general error handling routines for bad/insufficient data to draw a graph

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/206

**Comment by michaelwebbjisc** [comment]
Can you give me an example student?

**Comment by leebaylis** [comment]
actually two issues:
1) gloucester on which I tested it -- was a manifestation of https://github.com/jiscdev/data-explorer/issues/134
2) call was actually meant to be about USW (my bad), e.g. Geraldine Hall

**Comment by pdiveris** [comment]
I think it would be better if we added a date picker in the viz, instead of showing the last two months of whichever academic year.

**Comment by leebaylis** [comment]
Date picker has now been added as a result of another issue, and 'no data' popup has been added as a result of another issue.
