### ISSUE TITLE
xAPI Overview shows in new windows rather than the box to the left

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#108]
Submitted by MW

**Comment by robbristow-jisc** [comment]
I'm seeing the box OK, but I've noticed a behaviour that I think is maybe not what was intended. If you enter the XAPI, and click on 'OLDEST' link you get to see the oldest query (I presume). However, after that, and you want to look at the latest and clicking the 'Latest Statement' takes you back to the home page. 
However if you have gone to look at the Latest Statement the link at the top pf the box says 'Latest Statement' and takes you back to the home page as before.

**Comment by leebaylis** [comment]
opened new issue for this: https://github.com/jiscdev/data-explorer/issues/218
