### ISSUE TITLE
Year Flipper

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#109]
Year flipper returns no data for 2015 (and doesn’t flip back to show the data we do have for 2016.
 

 
If you set the year and then go Home the breadcrumb changes bit the data seems the same

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/64

From USW

**Comment by robbristow-jisc** [comment]
Still something funny about dates - I am not finding the date switcher that intuitive or consistent - probably need a longer description of what I mean

**Comment by leebaylis** [comment]
tickets exist for other issues: breadcrumbs and spinning ball on date change.
