### ISSUE TITLE
Layout issue with modules

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#111]
https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/225

![image](https://user-images.githubusercontent.com/8233360/26939954-e0ba6e5a-4c70-11e7-830d-72e845090965.png)

Submitted by USW

**Comment by robbristow-jisc** [comment]
I presume that this about the correct alignment of the module boxes? Look OK now on Staging with USW data
<img width="440" alt="screen shot 2017-08-04 at 14 26 04" src="https://user-images.githubusercontent.com/30286590/28970582-fb295d6e-7920-11e7-8797-9fdd4b2805da.png">
<img width="504" alt="screen shot 2017-08-04 at 14 27 49" src="https://user-images.githubusercontent.com/30286590/28970617-1c703bbe-7921-11e7-9ae2-071526a60232.png">

Tested on Demo as well:
<img width="446" alt="screen shot 2017-08-04 at 14 28 23" src="https://user-images.githubusercontent.com/30286590/28970648-37a2e9e0-7921-11e7-9a72-f39e90b9d632.png">
