### ISSUE TITLE
HOME PAGE>DEMOGRAPHIC EXPLORER Pulling in wrong data

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#114]
![image](https://user-images.githubusercontent.com/8233360/26946350-d8697bc2-4c86-11e7-8350-3f74e880011c.png)

Defaults to 14 day activity overview on ALL choices.
The arrow does nothing.

From USW

**Comment by michaelwebbjisc** [comment]
Feature removed

**Comment by leebaylis** [comment]
Is feature to be added into "next", or removed full stop?

**Comment by michaelwebbjisc** [comment]
Removed completely.  It was only there to show that the data existed.
