### ISSUE TITLE
Add Module Title

### ISSUE THREAD

**Issue by JemmaGreener** [jiscdev/data-explorer#115]
Add Module Title
Add Module Title (Think Adding Title is in the parking lot.In parking lot)
image
![image](https://user-images.githubusercontent.com/29302699/26970820-956858d0-4d02-11e7-9e2b-7c702226eafa.png)

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/251

**Comment by leebaylis** [comment]
Note from USW from https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/251: 

Looking at version.13 i think Module Title needs to be included anywhere we reference Module Instance ID.

**Comment by robbristow-jisc** [comment]
yes - seeing the module names in Module List view. Interestingly, they seem to take a kite while to be generated and then populate the table - well behind the other items in the table

**Comment by leebaylis** [comment]
@pdiveris presumably this is because they are being pulled in from a separate query?

**Comment by robbristow-jisc** [comment]
I guess the question has yet to be answered?

**Comment by michaelwebbjisc** [comment]
I'm going to close this, as technically it is done, but we need to change how it works, as it is making too many queries.
