### ISSUE TITLE
ExternalURL needs to resolve to text

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#117]
In tools graph

**Comment by leebaylis** [comment]
Visualisation of VLE content use for a student, in the case where a student has clicked on an external link and we have recorded that activity -- the text does not resolve?

**Comment by leebaylis** [comment]
Sorry Michael -- we can't find an example. Can you give a specific case?

**Comment by leebaylis** [comment]
We have figured this out on our own

**Comment by timstratton** [comment]
link not resolved to text on this occasion:


[tool use link not resolved.docx](https://github.com/jiscdev/data-explorer/files/1398504/tool.use.link.not.resolved.docx)
