### ISSUE TITLE
API for logging activity

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#125]
(eg from Study goal) for https://github.com/jiscdev/study-goal/issues/114

**Comment by leebaylis** [comment]
0.12 issues need tying off for testing or moving to 0.12.1, what is the status of this issue?

**Comment by michaelwebbjisc** [comment]
That ones done and in 0.12

**Comment by robbristow-jisc** [comment]
Can you explain what is to be tested here - I don't think I have access to anything that I could see to see what is happening here

**Comment by leebaylis** [comment]
Ah, don't worry rob, testing this one is on me
