### ISSUE TITLE
Use a variable to display the version in the footer

### ISSUE THREAD

**Issue by pdiveris** [jiscdev/data-explorer#129]
The version text appearing in the footer - ideally this should come from file autocreated when creating a new branch e.g. 0.11.2-45-and-54

**Comment by leebaylis** [comment]
0.12 issues need tying off for testing or moving to 0.12.1, what is the status of this issue?

**Comment by robbristow-jisc** [comment]
I see 'Version 0.12' on Staging and '0.12.1-ng' at the bottom of every screen I have looked at so far on both Dev and Staging

**Comment by leebaylis** [comment]
I'm assuming this is from the variable, great, closing!
