### ISSUE TITLE
Show progression codes.

### ISSUE THREAD

**Issue by JemmaGreener** [jiscdev/data-explorer#130]
Show progression codes, once pointing at LRW 1.3

**Comment by michaelwebbjisc** [comment]
I've changed the title of this one, as #137 covers making it compatible, this one is about showing the progression code.  Progression codes are for student on a course instance, so should show on the student overview page.

**Comment by michaelwebbjisc** [comment]
To test this you'll need to look at a 1.3 data set.  Drop me a slack message to find out which this should be.

**Comment by leebaylis** [comment]
Rob also needs to know which screen these codes have gone onto...

**Comment by leebaylis** [comment]
michael said look at city

**Comment by robbristow-jisc** [comment]
I see Progression codes! What they mean, I cannot say ;-)
