### ISSUE TITLE
"show" drop down arrow on HOME PAGE>INSTITUTION > Activity over time does nothing

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#131]
South wales reported, part of https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/230

clicking the show drop down arrow does nothing.

![image](https://user-images.githubusercontent.com/1846710/27862707-8472241c-617e-11e7-9027-910aa2a0c0f2.png)

**Comment by michaelwebbjisc** [comment]
this feature has been removed.
