### ISSUE TITLE
http:// does not redirect to https://

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#132]
e.g. browsing to http://x.data.alpha.jisc.ac.uk returns "this page isn't working"

**Comment by pdiveris** [comment]
This seems to have been resolved now thanks to ports.conf and the host conf.

**Comment by leebaylis** [comment]
Test results:
http://x.data.alpha.jisc.ac.uk redirects to https://datax.jisc.ac.uk ✔︎
http://datax.jisc.ac.uk redirects to https://datax.jisc.ac.uk ✔︎ 
http://x-staging.data.alpha.jisc.ac.uk DOES NOT redirect to https://x-staging.data.alpha.jisc.ac.uk ✘
http://x-dev.data.alpha.jisc.ac.uk redirects to https://x-dev.data.alpha.jisc.ac.uk ✔︎

**Comment by leebaylis** [comment]
staging was ports.conf -- opened port 80 and redirect now working
