### ISSUE TITLE
Selecting Home > Institution jumps down to All Datasets, looks like no viz has happened

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#133]
it takes you straight in here:
<img width="937" alt="screen shot 2017-07-05 at 13 50 03" src="https://user-images.githubusercontent.com/1846710/27865048-ef3faee0-6188-11e7-8f30-5294e19abbca.png">

but there is content above:
<img width="937" alt="screen shot 2017-07-05 at 13 50 13" src="https://user-images.githubusercontent.com/1846710/27865059-fad38484-6188-11e7-9369-93ade0d0c274.png">

I just kept clicking the activity over time and wondering why nothing was ever showing, it was not obvious at all that the content was above it at the top of the page

**Comment by robbristow-jisc** [comment]
Still not 100% happy about the way this works. At least we get to see the visualisation when clicking the Institution link on the home page, but where the browser chooses to place the top of that page is variable. This seems to be dependent on how scrolled the page is that you are clicking from, BTW. So if I have scrolled down the page to find the button, then when the Institution page loads, it is already semi-scrolled.

This seems to be consistent across Safari, Firefox and Chrome on MacOS

I would expect to click on  that button and the browser to land me on the page with the top of the page at the top of the browser - not at some variable place.

**Comment by michaelwebbjisc** [comment]
Closed as feature removed.  We'll add a new epic later to Next covering institutional views.
