### ISSUE TITLE
Demographic Explorer button's example visualisation is from a buggy viz

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#135]
raised by USW https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/232:

I think this visualisation  would show more that OVERSEAS. Could the text be removed.

![image](https://user-images.githubusercontent.com/1846710/27866905-01e1c982-6190-11e7-8d53-ffeeb92041ce.png)

basically can we find a nicer looking viz to screenshot on this button...

**Comment by michaelwebbjisc** [comment]
I took these out in version 0.12 as we already had a ticket for it.  At the moment I've replaced them all with black icons like the main home page.

**Comment by leebaylis** [comment]
Tested on dev; confirmed fixed
