### ISSUE TITLE
Compatibility with LRW 1.3

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#137]
new release of Data explorer reconfigured to use LRW1.3

**Comment by timstratton** [comment]
Have assumed that the scope of this does not include display of progression codes in DE and have raised separate ticket in FD.

**Comment by michaelwebbjisc** [comment]
Yes, this is just about making it work with the new Learning Locker API

**Comment by michaelwebbjisc** [comment]
To test this, you can use the Jisc 1.3 test LRW, which has 1.3 data.

**Comment by leebaylis** [comment]
rob -- this means on the select institution screen when you log in, there's a Jisc 1.3 LRW, check through all the screens and make sure you see what you expect!

**Comment by robbristow-jisc** [comment]
yes I do - but all the visualisations show the same graph. Is that supposed to be happening. Also some visualisations are empty, so hard to be sure what ought the there. Is there a Jisc with a different UDD that I can compare with?

**Comment by leebaylis** [comment]
City are on UDD 1.3 as well

**Comment by michaelwebbjisc** [comment]
I'm closing this as a general issue.  Instead we need to raise specific issues with any elements that aren't working.
