### ISSUE TITLE
Make default chart types customisable per institution ⚖108

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#138]
Phil: Graph type: weekly / daily bar chart (horizontal bar) not really useful for VLE activity by week. Perhaps have ‘default’ as VLE Activity by student. 
Phil: 
Use bar chart as default for VLE content as the pie chart is difficult to read after a dozen or so items.
Lee: is there ever a use case where it is useful by default -- maybe instead make default customisable

**Comment by michaelwebbjisc** [comment]
I don't think we'll be able to make this customisable per institution this sprint - it's too much. Instead we can change the defaults.

**Comment by leebaylis** [comment]
Bar chart is now default for VLE content -- moving to a future review

**Comment by michaelwebbjisc** [comment]
I'm closing this one, as it's no longer an active development task.
