### ISSUE TITLE
Better Breadcrumbs ⚖116

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#139]
from Glos:
If you click on an item within a VLE content list, there’s no return to the previous view

    If you click on back in the browser you have to select a module from scratch 
    There’s no breadcrumb 
    The only way back is to use the select visualisation route 
    Could we have a return to previous screen mechanism, browser navigation to previous screen, or a better breadcrumb?

**Comment by michaelwebbjisc** [comment]
Closing this as the new breadcrumbs are clearly implemented.  Further issues should get new tickets.
