### ISSUE TITLE
More informative display for modules ⚖104

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#140]
It would be useful to have both module names and codes displayed - see here in the attachment the 'Module Overview' only has the title, yet the initial screen only displays the code.

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/52

Module codes and module titles useful to show, so maybe need 3 rows (but without having to sacrifice too much vertical screen space – maybe smaller font?):

    Module Overview 
    Module Title 
    Module Code
LB: other calls too e.g. 
https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/247,
offering institution-level customisation of columns looking like best solution.

**Comment by pdiveris** [comment]
OK, I've simply added the Module Name in the Modules Listing view for now. 

This does not address https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/247 (offering institution-level customisation of columns) as there are some implications and some tough decisions required inorder to deal with this. Chief amongst this is a mechanism by which we map institution columns to an underlying schema. It is my opinion that this should be done *after* we move from UDD 1.2 and 1.3 to 1.4 which, being SQL based, would allow us to do some jazzy stuff on teh SQL level. Obviously this doesn't cover the xAPI data, but still it will be of great help.

**Comment by robbristow-jisc** [comment]
Looks good on both Dev and Staging

**Comment by leebaylis** [comment]
spun off https://github.com/jiscdev/data-explorer/issues/216 for the larger customisation
