### ISSUE TITLE
Rationalise scales ⚖104

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#141]
glos:
e.g. VLE content bar chart – shows half points when top value is low e.g. 3, but you can’t have half values

**Comment by pdiveris** [comment]
This has been fixed now in both 0.12.1 and 0.13 and deployed on Dev and Staging respectively, please test.

**Comment by robbristow-jisc** [comment]
Can't see any sign of half values anywhere - looks good to me
