### ISSUE TITLE
add API calls to capture app data ⚖84

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#145]
SG team added: 
The following measures will be needed, so API calls will need to allow this information to be stored as appropriate in a database:

- App downloads (per institution)
- App uninstalls (per institution)
(LB: do the apple and play stores do this, or is there a hook in the app code to trigger on install/uninstall?)

- Distinct users 
- Logins (per student) 
- Total
- Avg # times per month per user
(LB: by storing user login, device and timestamp)

-  Activity / page views:
  - Totals
  - Average per visit
  - By section e.g. log, stats, targets
(LB: by storing some data to be determined every time a user changes page or view?)
 
- Average time of site
(LB: by storing user logout or app termination device and timestamp)

**Comment by leebaylis** [comment]
https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/256

**Comment by michaelwebbjisc** [comment]
Just reviewing this.   

The API won't quite do this.  What it will do is allow a call like this:
```
 api.x.data.alpha.ac.uk/sg/log?verb=xxx&contentID=xxx&contentName=xxx&modid=xxxx 
```
which will be converted to xAPI according to the mobile recipe.

**Additional notes:**

These two aren't possible.  Google Play and Apple only have total app downloads:
App downloads (per institution)
App uninstalls (per institution)
(LB: do the apple and play stores do this, or is there a hook in the app code to trigger on install/uninstall?)

**These should be dealt with by general system/platform level reporting, as Study goal is no different to VLE, Library etc:**
Distinct users  - > New request need for institutional report
Logins (per student)  -> part of student overview
Avg # times per month per user  - > Times per month/week, not average.  -> part of student overview
By section e.g. log, stats, targets  -> part of student overview and institutional

**And parked for later:**

Average time of site  - >  This is one for the future. The same issue affects all systems, and requires some sort of data aggregator to look at last activity before next login.

(LB: by storing user logout or app termination device and timestamp)

**Comment by michaelwebbjisc** [comment]
This one is now complete and merge to 13.0 on dev

example call:

https://api.x-dev.data.alpha.jisc.ac.uk/sg/log?verb=viewed&contentID=stats&contentName=stats%2-overview&modid=mod101 

example response:

["8fafe032-1fac-45ff-b42f-007df904a72d"]

and a bad one:

https://api.x-dev.data.alpha.jisc.ac.uk/sg/log?verb=viewdded&contentID=stats&contentName=stats%2-overview&modid=mod101 

{"error":true,"success":false,"message":["`viewdded` should be a valid `Locker\\XApi\\IRI` in `statement.verb.id`"],"code":400,"trace":"`debug` must be `true` in the App's config to get a trace."}

verb should be loggedin or viewed
