### ISSUE TITLE
Turn off page caching until DE CSS etc are a little more stable

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#147]
the new CSS was not being rendered properly in the browsers of previous users, the browser had cached the old CSS files. Can we put metadata in the pages to let browsers know either not to cache or to refresh the cache more regularly whilst we are in such a rapid release phase?

**Comment by pdiveris** [comment]
When a CSS is loaded add a ?x=23874623746 at the end so that the browser doesn't cache it.

**Comment by pdiveris** [comment]
Added a version suffix to the CSS loader. It means that when we move to a new version the CSS url will be different and the browser forced to reload it. This version string is set as a constant in a source called aux.scripts.js.

**Comment by leebaylis** [comment]
michael has used the suffix technique across the board and this tests OK for removing caching
