### ISSUE TITLE
site explorer/admin PIDs need to be converted to http by the form at #/admin/addusers

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#149]
if people put https://* in the pid field the form should submit http:// instead, some sites were inconsistent so the app converts pids returned by shib to http. This causes a problem if the sails d/b contains https...

**Comment by pdiveris** [comment]
http://localhost:3000/#/admin/addusers

**Comment by pdiveris** [comment]
This has been fixed in 0.12-94-2

https://bitbucket.org/jiscdigitalfutures/datax-client/commits/db4eb96d9ddfccc59f86335146042472ee2e866a

**Comment by pdiveris** [comment]
Thanks Lee - will follow this patter in the future.

**Comment by michaelwebbjisc** [comment]
Should the milestone on this one change to 0.12?

**Comment by leebaylis** [comment]
oh -- not intentionally, but it does seem to have been committed to it!

**Comment by leebaylis** [comment]
Tested.

Aha! My bad, some url's contain multiple instances of https and it is only the one at the very beginning of the string which needs to be converted to http
e.g.

https://idp.jisc.ac.uk/idp/shibboleth!https://sp.data.alpha.jisc.ac.uk/shibboleth!Plns8hSFdu7z85H2F12UfDzQUhk=

needs correcting to 

http://idp.jisc.ac.uk/idp/shibboleth!https://sp.data.alpha.jisc.ac.uk/shibboleth!Plns8hSFdu7z85H2F12UfDzQUhk=

but is currently getting corrected to

http://idp.jisc.ac.uk/idp/shibboleth!http://sp.data.alpha.jisc.ac.uk/shibboleth!Plns8hSFdu7z85H2F12UfDzQUhk=

this has now broken the #/admin/addusers feature completely on dev

**Comment by michaelwebbjisc** [comment]
I'm closing this, as it's no longer relevant as Jisc are releasing eppn now.
