### ISSUE TITLE
'true' Demo data available ⚖ 92

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#151]
- demo data available, preferably via the same mechanism as real data i.e. the API so it is a true demo / does not introduce bugs which are otherwise irrelevant

**Comment by michaelwebbjisc** [comment]
I'm not sure about this one.  For ages we used true demo data, but it doesn't work well for Demos, as the the demo person needs the data to be consistent when ever they login.  I actually think the demo mode is fine as it and don't think we should change it.  The code could be more elegant, but the mode itself not works for story telling, and that's the really important thing.

I wonder if this is really about test data instead?

**Comment by leebaylis** [comment]
revisiting this in infrastructure
