### ISSUE TITLE
Typo in menu (UDD Overviewr instead of Overviewer)

### ISSUE THREAD

**Issue by pdiveris** [jiscdev/data-explorer#156]
See this 

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/292

**Comment by pdiveris** [comment]
"closed" - please test

**Comment by leebaylis** [comment]
Oops -- still wrong, should be "Overview" not "Overviewer"

**Comment by pdiveris** [comment]
dammit

leebaylis wrote:

**Comment by robbristow-jisc** [comment]
Looks fixed on Dev and Staging
