### ISSUE TITLE
Student Name Wrong

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#159]
USW raised:
![image](https://user-images.githubusercontent.com/1846710/28566563-6af90a6a-7127-11e7-9fb9-dac9d9c56c98.png)
I think Alex Crawford appears on all students.

**Comment by robbristow-jisc** [comment]
Looks good - testing about a dozen students and their names all show up as I would expect

**Comment by robbristow-jisc** [comment]
Looks good - tested about a dozen students and their names all show up as I would expect
