### ISSUE TITLE
Cannot browse to earlier years when selecting date range in Module Overview

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#161]
and yet skipping back through the months reveals that earlier years are available for selection.

![screen shot 2017-07-25 at 17 06 46](https://user-images.githubusercontent.com/1846710/28582006-d8cff2cc-715b-11e7-810c-b9e9682ec30a.png)

**Comment by robbristow-jisc** [comment]
Still able to take the data picker back beyond the date at which the data seems to start - see attached. Good UI practice would be to make any date earlier than there is data for unavailable (greyed out).

I want to raise another issue about date pickers. 

Try this - go to Glos, select a Module (AC4002/A12/UMS) and set the date range to start on 2017-05-01 (also, can we have UK formatted dates, please?) So  - I see a nice list students ordered by VLE activity. But then I click on Ellie Russell - and then I find that when I look at her detail, what I see is information that is now only starting from 2017-07-29. So to see Ellie's VLE access information from 1st May I must now reset that start date picker. Would make me gnash my teeth in time if I was using this for real!

**Comment by robbristow-jisc** [comment]
Not sure if that answers the question, but there are clearly some issues here

**Comment by michaelwebbjisc** [comment]
Tested and confirmed.  The secondary issue has been addressed by https://github.com/jiscdev/data-explorer/issues/243.
