### ISSUE TITLE
 Drop down menus are out of synch with home screen items 

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#163]
In particular the new site config feature is not available in the menus, but they should ideally be built from the same source

**Comment by robbristow-jisc** [comment]
Yep - that looks good. The menu item appears in the drop down for Site Admin - and clicking it takes me to the Configuration page.

One pint - although I am clicking on an icon or in this case, a menu option called "Site Config" the page I get to is just called Configuration, and I notice that the Breadcrumb item is merely Config. 

FWIW, it might make sense to have some consistency of naming here.

**Comment by leebaylis** [comment]
Agreed -- @pdiveris , let's standardise on 'configuration' and let the 'site admin' parent convey the 'site' part!

**Comment by pdiveris** [comment]
OK, I've released a fix for this on DEV, please have a look..

**Comment by robbristow-jisc** [comment]
Happy now. ;-)
