### ISSUE TITLE
Column order in Site Explorer>All Tutors>Tutor view has been broken between 0.11 and 0.12

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#166]
e.g. USW on staging:
<img width="1273" alt="screen shot 2017-08-02 at 09 35 39" src="https://user-images.githubusercontent.com/1846710/28864997-3d0c5824-7766-11e7-81f1-1669d4fc2699.png">

vs the old layout on live:
<img width="1273" alt="screen shot 2017-08-02 at 09 37 13" src="https://user-images.githubusercontent.com/1846710/28865009-4b1b56cc-7766-11e7-8ef7-90f57f84d00c.png">

**Comment by pdiveris** [comment]
I've fixed this, [committed](https://bitbucket.org/jiscdigitalfutures/datax-client/commits/50247041e093f0b266b20aa0693c0419c5a6ab79),[pushed and deployed on x-dev.

**Comment by leebaylis** [comment]
...but not labelled it for testing or assigned it to Rob :p

**Comment by pdiveris** [comment]
Um.. I have added a postit note on my screen now. Seriously.

**Comment by robbristow-jisc** [comment]
Looks fixed on Dev. Now everything lies up under the right column heading
