### ISSUE TITLE
Use comma to separate 1000's ⚖100

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#167]
Institutions, Demographic Explorer, tooltips 
· Needs a comma “1,791”
But may be elsewhere as well!

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/63

**Comment by robbristow-jisc** [comment]
Ok - well, I can see the comma now if I hover over one of the bars - but I am not seeing the pie chart that is referred to in the original ticket.  What I see is a the same bar chart with "14 Day Activity Overview" regardless of which of the Demographic parameters I select. See screenshot

This is showing aa being 0.12.1, BTW.

<img width="1310" alt="screen shot 2017-08-15 at 17 13 10" src="https://user-images.githubusercontent.com/30286590/29324721-0aad56ae-81dd-11e7-9976-17f77af13c2b.png">

**Comment by leebaylis** [comment]
I think the pie chart was removed as the result of another ticket -- this one's been floating about for a while. 
The RHS menu is covered in https://github.com/jiscdev/data-explorer/issues/114
