### ISSUE TITLE
Add Numeric values to bar chart tooltips

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#170]
See Rob's suggestion on https://github.com/jiscdev/data-explorer/issues/96#issuecomment-319930379

show the activity count (numeric size of bar) in the tooltip.

**Comment by pdiveris** [comment]
OK, I've worked on *all* tooltips in Modules/Overview. That is, I've reformatted the bar, pie and scatter chart tooltips as per screens attached. I will be porting those changes to **Students** and **Tutors** next.

**Comment by leebaylis** [comment]
great stuff! Reassigned to Rob!

**Comment by robbristow-jisc** [comment]
yes - see the values in the tooltips for all the graphs I have looked at so far
