### ISSUE TITLE
Student Overview > Assessments over time description of timescale does not line up with dates

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#171]
e.g. Ginnelly, USW -- "last two months" from today's date should be 3/6/17 - 3/8/17 but instead it is showing 3/5/17 - 31/9/17!

<img width="1273" alt="screen shot 2017-08-03 at 14 12 57" src="https://user-images.githubusercontent.com/1846710/28923519-44d8a38c-7856-11e7-8ff4-2663f5ba6180.png">

**Comment by pdiveris** [comment]
I think that they **all** show 3/5/17 - 31/9/17. I also think that this is a fine set of dates so I am only reluctantly looking at this issue now!

**Comment by michaelwebbjisc** [comment]
Tested as incognito and existing user - working fine now. Fixed as part of date pickers on this screen.

![image](https://user-images.githubusercontent.com/8233360/31561008-708a7e4e-b04e-11e7-9649-75c8ed379b13.png)
