### ISSUE TITLE
Activity with Assessments tries to draw Attendance activity instead, fails

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#172]
e.g. USW, Ginnelly

![screen shot 2017-08-03 at 14 23 50](https://user-images.githubusercontent.com/1846710/28923863-6eb121b0-7857-11e7-90db-e5c02a5da30b.png)

**Comment by pdiveris** [comment]
So this should be fixed now in 0.13. I have deployed this on staging and tested. It basically happened when there was no data for the visualisation, as the init code for the chart was erroneously located in the data transformation loop. I have also pulled the change into 0.12.1 and deployed on dev. Please test.

**Comment by robbristow-jisc** [comment]
With that student (and one or two others that I have found with relevant data) I can see a different visualisation that says it is "Overall Activity with Assessment Grades". However, looking at that I see one dot with an activity of 11 - and I don't really know what that means. The vertical axis sys "Values" which does not seem that helpful

**Comment by michaelwebbjisc** [comment]
I've closing this one as the comment refers to a different issue, covered in https://github.com/jiscdev/data-explorer/issues/207
