### ISSUE TITLE
USW student 16015797 overview graph does not render on dev

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#173]
Tired clearing my cache just in case -- Works fine on staging:
![screen shot 2017-08-07 at 13 18 42](https://user-images.githubusercontent.com/1846710/29026299-fb4b90d8-7b72-11e7-862f-549c62f4de8c.png)

but not on dev:
![screen shot 2017-08-07 at 13 19 39](https://user-images.githubusercontent.com/1846710/29026327-1a60a47c-7b73-11e7-97a8-d04e30756131.png)

**Comment by pdiveris** [comment]
OK, this has been fixed by virtue of a fix for another issue pertaining to USW (well, to the lack of a data for a student of USW for a period,) committed/pushed and deployed onto dev. 

**Please clean your browser cache!**

**Comment by robbristow-jisc** [comment]
Still dies not look the same on Dev and Staging. Staging is as I would expect - Dev looks like it is not drawing properly on the page
![staging](https://user-images.githubusercontent.com/30286590/30870379-a3b344ac-a2db-11e7-9902-a954d947158d.png)
![dev](https://user-images.githubusercontent.com/30286590/30870382-a427b850-a2db-11e7-87eb-6fa7ea051e99.png)

**Comment by leebaylis** [comment]
flagged in user group call as well, but dev (0.13.1f) is now behind staging (0.13.5b) and this problem doesn't exist on live. suggest we shift dev to 0.14.

**Comment by michaelwebbjisc** [comment]
I've closed this, as 16015797 is no longer a student, so we can't replicate.  Will need a fresh example to reopen.
