### ISSUE TITLE
student module overview drop down no longer changes the graph since moving 0.11.1 - 0.12.1

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#174]
This effectively means we broke the build I think -- e.g. on live:

![screen shot 2017-08-07 at 13 23 26](https://user-images.githubusercontent.com/1846710/29026532-28e6b0da-7b74-11e7-8ff9-521422c4c6ee.png)

but on staging:

![screen shot 2017-08-07 at 13 23 44](https://user-images.githubusercontent.com/1846710/29026546-33a2367a-7b74-11e7-915a-9e7c374b1e86.png)

**Comment by timstratton** [comment]
Freshdesk ticket is 325

**Comment by pdiveris** [comment]
Right, this is not relevant anymore. Following a chat with MW I've removed the option from the menu altogether as this is now superseded by 
![pasted_image_at_2017_08_14_08_20_pm](https://user-images.githubusercontent.com/1022373/29287874-aa980f6a-812e-11e7-8775-cd33c74f4709.png) and it shouldn't be there.

**Comment by robbristow-jisc** [comment]
Yes - no sign of that option in the "Select Visualisation" drop down menu
