### ISSUE TITLE
Standardise nomenclature referring to year -- e.g. either '2015 - 2016' (preferred, I think) or '2015'

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#176]
see https://github.com/jiscdev/data-explorer/issues/51#issuecomment-320917869

**Comment by pdiveris** [comment]
Changed labels wherever I could to "2015-2016" 0.12.x. Pulled into 0.13. Released in both dev (0.12.1) and staging (0.13.)

**Comment by robbristow-jisc** [comment]
Good and bad on this.
1. Good - When I change the year in the drop down I see the 2015-2016 or 2016-2017 in the breadcrumbs and in the Student Overview.
2. Not so good - When I change the Academic year, I still see the single year in the blue conformation box that appears

**Comment by pdiveris** [comment]
Update the pop up you get when changing the year to be consistent (i.e. 2015-2016)

**Comment by michaelwebbjisc** [comment]
This failed on the year changer, which has now been removed, so I'm closing.
