### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#178]
The ability to send messages to the student on study goal from the student overview page. Please add a button to message the student from this page
NOTE!! using this feature on an institution's data will actually message a student -- test with care or use the UoJ Blue institution!

**Comment by robbristow-jisc** [comment]
So, I see the rather small message box, and the send button (UoJ Blue 1.2). I write some text in the box and click send but nothing appears to happen. Is that what is intended? I think that at least, the message should disappear, but preferably I'd like to see a confirmation that it has been sent

**Comment by michaelwebbjisc** [comment]
Feature moved to Next.
