### ISSUE TITLE
Add option to config to hide push notification message

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#179]
USW raised Ticket: https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/330

Could we add the function to disable the messaging student option within Site Config please

![image](https://user-images.githubusercontent.com/1846710/29455853-b506bee0-840a-11e7-869c-ac9be79c7ae0.png)

**Comment by pdiveris** [comment]
Added option to config to hide push notification message. It has been worked on 0.12.1, committed, pushed and merged into 0.13. Consequently the feature has been released on Dev/0.12.1 and Staging/0.13. 

Please test.

**Comment by robbristow-jisc** [comment]
Seems to be working OK. I can turn this off and on in the Configuration screen and then see the box to send a message in the Student Overview screen. BTW, on my screen the message box is right at the bottom, and often out of view. I wonder if though could be given changing its position?

**Comment by leebaylis** [comment]
Agreed with Petros -- we'll move the student info pane into the header and move the message to the top of the column

**Comment by robbristow-jisc** [comment]
Makes sense

**Comment by leebaylis** [comment]
raised https://github.com/jiscdev/data-explorer/issues/193 to cover this
