### ISSUE TITLE
Add VLE mod id where mod ID and Mod instance ID are shown

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#189]
relates to https://github.com/jiscdev/data-explorer/issues/140 -- USW would like the VLE_MOD_ID to be shown as well in both the module list and on the module overview, if we can fit it in.

Freshdesks

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/331
https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/323

**Comment by michaelwebbjisc** [comment]
I've only put this on the module overview.  This is largely a legacy issue because it's relating to how usw used to handle module instance IDs. Self testing as trivial:  

![image](https://user-images.githubusercontent.com/8233360/31609066-96f9adca-b26a-11e7-9f37-759902eda702.png)
