### ISSUE TITLE
Basic demographic info about student

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#19]
From Pathfinders meeting

**Comment by leebaylis** [comment]
Please resubmit as enhancement using the form and provide context
https://forms.office.com/Pages/ResponsePage.aspx?id=TTn5SBSKJ02CpvNfEjYSBd2sT89nF9RJhClxPe2uce9UNDZVWFlXVUY2TTZZSUxEUFRTSVUzMllDMy4u
