### ISSUE TITLE
move the student info pane into the header (move the push message to the top of the column  now seperate issue)

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#193]
see https://github.com/jiscdev/data-explorer/issues/179

**Comment by michaelwebbjisc** [comment]
Fixed as part of #206

**Comment by robbristow-jisc** [comment]
Funny - still at the bottom (USW on Staging - v0.13.5b) See screenshot
<img width="1040" alt="screen shot 2017-10-04 at 17 21 08" src="https://user-images.githubusercontent.com/30286590/31187042-73c282e6-a928-11e7-93be-1874708e1c58.png">

**Comment by leebaylis** [comment]
Ah, Michael has made this just about the first part, @robbristow-jisc -- so moving the info to the header. He's spun off a separate call for the push notification move

**Comment by robbristow-jisc** [comment]
In that case it looks good - I see the student information in teh header above the visualisations - see attached.
<img width="1005" alt="screen shot 2017-10-06 at 11 38 15" src="https://user-images.githubusercontent.com/30286590/31274481-fbfa9c4e-aa8a-11e7-85f5-b077bce32029.png">
