### ISSUE TITLE
Institution URL for DE 

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#195]
USW asked:

We’d like to use https://datax.southwales.ac.uk as the url: 

This request has made its way to the network team. We can't offer you a URL redirect as we don't run any webservers. What we can offer is to put a DNS alias (CNAME) in place. However for that to work the remote server will need to know and be set-up for the DNS alias. If you really need a URL redirect then this will need to go to our web team for them to set-up a local webserver to do the redirection."

petros, what are the implications of using a DNS CNAME -- will they also need to set up an api CNAME?  will anything else break?

**Comment by leebaylis** [comment]
decision to tell them to just do it and we'll see what breaks

**Comment by pdiveris** [comment]
Have we asked USW to add the DNS entries?

**Comment by pdiveris** [comment]
And yes, they need a CNAME for both

**datax.southwales.ac.uk->datax.jisc.ac.uk**

and

**api-datax.southwales.ac.uk->api-datax.jisc.ac.uk**

**Comment by leebaylis** [comment]
Have just asked

**Comment by leebaylis** [comment]
question answered
