### ISSUE TITLE
Student ID shows up in place of student name sometimes

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#196]
USW https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/338

When looking at activity by student from Module overview some students names are replace by their ID 

![image](https://user-images.githubusercontent.com/1846710/29995840-d14280a8-8fea-11e7-80a2-3cde7dfc8213.png)

**Comment by leebaylis** [comment]
Suspect this is a duplicate of 105 -- we'll work on that and check this when that's resolved

**Comment by michaelwebbjisc** [comment]
Yes, duplicate.  I'm closing this one so we've only got one to look at.
