### ISSUE TITLE
How is Completed Module determined

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#197]
USW: https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/339

What is it that determines a completed module as show in student overview

![image](https://user-images.githubusercontent.com/1846710/29995875-b6c89b30-8feb-11e7-8a68-236564742475.png)

**Comment by leebaylis** [comment]
related to https://github.com/jiscdev/data-explorer/issues/215

**Comment by michaelwebbjisc** [comment]
It's from the studentmoduleinstance.RESULT - if has 1 or 2 (ie pass or fail) then it's classed as completed.
