### ISSUE TITLE
break down risk factors ⚖80

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#209]
from Jisc:
   The specific screen related to the enhancement.

Student - Module View - Risk Factors or Module view risk score

    Context: Why and how will the enhancement be used? 

To show a breakdown of the risk factors associated with a predictive score for a module

    Description: Who will use this enhancement? What are they trying to do? What is the desired outcome? 

This is for tutors to see the a breakdown of the risk factors relating to a risk score. At present this shows  bar chart where the higher the bar the more that factor is associated with the risk i.e. online activity, demographics, attendance, attainment. They don't see how these relate to a risk score of 40% and it will be even more meaning less if we are using OLAP risk percentages and pseudolap risk factors.
Feedback from institutions has suggested that traffic light indicators would be better and easier to interpret.
Some sort of collated risk factors across a course rather than module level
To be able to drill down on a risk factor and see what makes up that risk e.g. VLE/attendance use against an average, demographics weightings etc.

    The date if the enhancement required for a timed event (e.g. start of module)?

By Sept 2017 for start of year, but would be good to test it over the summer

    How many people will use the feature?

All tutors using Data X will want to see this.

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/216

**Comment by michaelwebbjisc** [comment]
This needs breaking down into a number of issue.  I think some of it is referring to the original version of pseuoLAP, and so no longer relevant.

'This is for tutors to see the a breakdown of the risk factors relating to a risk score. At present this shows bar chart where the higher the bar the more that factor is associated with the risk i.e. online activity, demographics, attendance, attainment. They don't see how these relate to a risk score of 40% and it will be even more meaning less if we are using OLAP risk percentages and pseudolap risk factors.'

The bar chart has been retired.  These have been replace by the out put from O/JAP, which is a single figure, and traffic lights from the relevant calculations from what was Pseudo LAP (attendance, achievement, virtual engagement).  So I think I useful addition would be to see how the traffic light calcuation is arrived at.  This is a feature request to PLAP in the first instance, as that has to be added to the xAPI it produces.

Course level risk is a function of JLAP, so when that produces output at course level then we can open a ticket to get that displayed.

**Comment by leebaylis** [comment]
Superceded by introduction of JLAP and traffic light outputs. Create an issue for these.

**Comment by michaelwebbjisc** [comment]
Superceded by TLC.
