### ISSUE TITLE
Add institution logos to DE once logged in ⚖100

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#210]
USW raised: 
Would like to be able to add USW logo's and some student related images to the home screen.
Also an idea for branding -- see image in ticket, clicking the play button on the login screen opens either a default or institution provided  Powtoon welcoming staff to the app?

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/228

**Comment by michaelwebbjisc** [comment]
Closed for now.  May revisit customisation as paid extra.
