### ISSUE TITLE
Student overview details empty when accesed through module lead view

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#213]
Glos reported: 

All Tutors > Module Lead View > View module > VLE Activity - Student use distribution and double click a student takes me to 
https://x.data.alpha.jisc.ac.uk/#/student-overview/s1603931

All Students > search takes me to 
https://x.data.alpha.jisc.ac.uk/#/student-overview/1603931

i.e. when accessed from the viz the s is appearing in the URL/student ID and so the student is not found

**Comment by leebaylis** [comment]
https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/356

**Comment by robbristow-jisc** [comment]
Ok - Looks good. I can now see the student detail when clicking through from the visualisation and from the search. The 's' is gone from the URL
