### ISSUE TITLE
assessment over time graph has started going back to 1970

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#214]
![image](https://user-images.githubusercontent.com/1846710/30700589-df577d84-9edf-11e7-8ad8-93fdc7782797.png)

 I don't think it's anything in the data:

https://jiscv2.learninglocker.net/api/jisc/v1.2.7/studentassessmentinstance?select={"ASSESS_DUE_DATE": 1,"GRADE_DATE": 1, "_id": 0}&query={"$or": [{"ASSESS_DUE_DATE": {"$lt": "2000-01-01T00:00:00.000Z"}}, {"GRADE_DATE": {"$lt": "2000-01-01T00:00:00.000Z"}}]}&limit=1

returns []

**Comment by michaelwebbjisc** [comment]
I'm closing this one off as I can't recreate it.  It may have been fixed by the changes to the date pickers (or their introduction).  See screenshot

![image](https://user-images.githubusercontent.com/8233360/31558634-a48c9e9c-b045-11e7-8f0c-0c0df84fdcf2.png)
