### ISSUE TITLE
Internal business logic for predictions

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#215]
https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/359
glos raised:
Please can we confirm:
1.     That when a module is deemed to be complete that DE will no longer show a prediction for a student on that module?
2.      That "Pass prediction" in Config needs to be set on to view predictions from OLAP? PseudoLAP?

Also,
What data is used by DE to determine when a module is deemed to be complete?

**Comment by leebaylis** [comment]
related to https://github.com/jiscdev/data-explorer/issues/197

**Comment by michaelwebbjisc** [comment]
Yes, as for the other question #179, once we have pass or fail it moves to completed, based on RESULT.

For the other, the prediction in the gauge is  from oLAP, and the two traffic lights calculated by PLAP.

**Comment by michaelwebbjisc** [comment]
https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_a_module_instance.md#mod_result

**Comment by leebaylis** [comment]
That answers the related question, but this question was can we confirm that if the module is complete, the prediction **will no longer show**, and also can we confirm that predictions from OLAP and PLAP **will not show** if pass prediction is turned off. testing I think the answer to 2) is yes, but 1 I don't know...
