### ISSUE TITLE
Customisable module columns ⚖104

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#216]
spun off from https://github.com/jiscdev/data-explorer/issues/140

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/247,
offering institution-level customisation of columns looking like best solution.

there are some implications and some tough decisions required inorder to deal with this. Chief amongst this is a mechanism by which we map institution columns to an underlying schema. It is my opinion that this should be done after we move from UDD 1.2 and 1.3 to 1.4 which, being SQL based, would allow us to do some jazzy stuff on teh SQL level. Obviously this doesn't cover the xAPI data, but still it will be of great help.

**Comment by michaelwebbjisc** [comment]
I think we should close this now, as it was related to the way USW were providing UDD data.  They are now providing it in a more standard way, so this is resolved.
