### ISSUE TITLE
xapi overview latest statement link takes you home

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#218]
forked from https://github.com/jiscdev/data-explorer/issues/108

I'm seeing the box OK, but I've noticed a behaviour that I think is maybe not what was intended. If you enter the XAPI, and click on 'OLDEST' link you get to see the oldest query (I presume). However, after that, and you want to look at the latest and clicking the 'Latest Statement' takes you back to the home page.
However if you have gone to look at the Latest Statement the link at the top pf the box says 'Latest Statement' and takes you back to the home page as before.

**Comment by michaelwebbjisc** [comment]
Yes, thats not meant to do that!

**Comment by michaelwebbjisc** [comment]
SImple fix. No further testing required.
