### ISSUE TITLE
 "demo" on screens for attendance tracking is displayed 

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#219]
Abertay raised:

https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/368

Can we remove "demo" from the attendance tracking screens?
![image](https://user-images.githubusercontent.com/1846710/30961086-f44300c6-a43c-11e7-9b65-86decb73aa4f.png)

![image](https://user-images.githubusercontent.com/1846710/30969472-6055be62-a45a-11e7-8c46-4318152a7937.png)

**Comment by leebaylis** [comment]
Abertay feel this is urgent as they are going live

**Comment by michaelwebbjisc** [comment]
I'll pick that one up.  Ironically it was there to show that this was indeed a demo visualisation, and not intended for production use.

**Comment by timstratton** [comment]
It's still present in V1.0 on staging

**Comment by leebaylis** [comment]
Hi Tim, 
We're not using github anymore -- we're on the Jira board now
https://jiscdev.atlassian.net/secure/RapidBoard.jspa?rapidView=270&selectedIssue=LADE-30

I'll reopen this there
