### ISSUE TITLE
Positive stories

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#22]
As well as alerts for risk it would be good to recognise string engagement/achievement and praise the student.

From Pathfinders Meeting

**Comment by leebaylis** [comment]
Please resubmit as enhancement using the form and provide context
https://forms.office.com/Pages/ResponsePage.aspx?id=TTn5SBSKJ02CpvNfEjYSBd2sT89nF9RJhClxPe2uce9UNDZVWFlXVUY2TTZZSUxEUFRTSVUzMllDMy4u
