### ISSUE TITLE
Sort attendance events by date then time, not by time then date

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#220]
<img width="767" alt="screen shot 2017-09-28 at 11 59 23" src="https://user-images.githubusercontent.com/1846710/30963260-b8bb0302-a444-11e7-9e1d-a6e570112ade.png">

**Comment by michaelwebbjisc** [comment]
Sorted as part of 1.0

**Comment by michaelwebbjisc** [comment]
See example:

![image](https://user-images.githubusercontent.com/8233360/31561690-96efeff4-b050-11e7-8f6d-7505484745e2.png)
