### ISSUE TITLE
multiple registrations in attendance

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#222]
Abertay raised:
https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/374

need to determine first whether this is the result of the student registering for attendance multiple times or a data glitch. 

if multiple registrations, we need to block somehow -- if data glitch, find and fix. 

![image](https://user-images.githubusercontent.com/1846710/31124694-788c8fd8-a83d-11e7-8cb9-7a6743df2d7c.png)

**Comment by michaelwebbjisc** [comment]
It's students registering multiple times.

**Comment by michaelwebbjisc** [comment]
This is superceed by https://github.com/jiscdev/data-explorer/issues/231

as a secondary issue, the api now no longer sends subsequent xapi statements once the person has checkin in once.
