### ISSUE TITLE
Clicking on any student's pass probability module in Demo mode takes you to Alice Scott's module overview

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#225]
![screen shot 2017-10-03 at 23 40 31](https://user-images.githubusercontent.com/1846710/31152504-64cf50dc-a894-11e7-9830-899610409e66.png)
![screen shot 2017-10-03 at 23 40 46](https://user-images.githubusercontent.com/1846710/31152508-6ac6687c-a894-11e7-900d-ac60ba5c0c45.png)

**Comment by michaelwebbjisc** [comment]
That's by design.   Demo mode only works if you follow the demo script.  Remember this is for internal Jisc use only.
