### ISSUE TITLE
Module overview offers Column and Bar graph types but they draw the same thing

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#226]
![screen shot 2017-10-04 at 09 37 45](https://user-images.githubusercontent.com/1846710/31166774-cc65287c-a8e7-11e7-8772-13f39860d0ae.png)

**Comment by michaelwebbjisc** [comment]
That was actually by design. Early on people want a choice how the data was shown, so the API gives you a choice of valid display types (bar, column, pie) etc.  Are you sure we want to remove that?

**Comment by michaelwebbjisc** [comment]
Ah, I see what you mean.  For me it actually only works the first time I use it, then it doesn't change the chart type.

**Comment by michaelwebbjisc** [comment]
I've now just removed this feature - we can bring it back again at a later date.
