### ISSUE TITLE
Site Explorer/Institution/Demographic explorer now broken again

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#227]
draws 14 day activity overview. Checked in live and staging. 

What happened? I thought this one had been fixed already

**Comment by pdiveris** [comment]
Erm.. no idea. Looking to Github for clues as it was fixed.

**Comment by michaelwebbjisc** [comment]
Institution overview removed.  These were really just demos, apart from the course overview, which needs to go to next.
