### ISSUE TITLE
#/admin/addusers no longer has any institutions in the drop down list on live or staging

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#237]
<img width="1212" alt="screen shot 2017-10-05 at 12 59 26" src="https://user-images.githubusercontent.com/1846710/31226175-0bc456b0-a9cd-11e7-97e8-eb9ba1882591.png">

**Comment by michaelwebbjisc** [comment]
![image](https://user-images.githubusercontent.com/8233360/31556087-634c8cbc-b03b-11e7-8bf8-4e31ff9d0a7b.png)

Confirmed fixed.
