### ISSUE TITLE
Change 'no vle data' popup to fade out rather than have to click

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#247]
This is my number one request after using it a lot!

**Comment by leebaylis** [comment]
original ticket https://github.com/jiscdev/data-explorer/issues/97 still open but we'll break this part out here.

backed by feedback from user group: Make yellow popups fade after a few seconds rather than have them need clicking on...

**Comment by michaelwebbjisc** [comment]
Simple fix - any remaining ones can be changed as we come across them.
