### ISSUE TITLE
Settings doesn't work if its not been used before.

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#248]

**Comment by michaelwebbjisc** [comment]
I'll pick this up as part of 1.0 as I need it to work for that release

**Comment by leebaylis** [comment]
settings?

**Comment by michaelwebbjisc** [comment]
The config settings, like showPredications, showAttendanceData etc.

**Comment by michaelwebbjisc** [comment]
Tested exhaustively as part of developing other features. No further testing required.
