### ISSUE TITLE
Display student assessment submission data

### ISSUE THREAD

**Issue by timstratton** [jiscdev/data-explorer#27]
Edge Hill want to be able to see when students have submitted assessments.

**Comment by michaelwebbjisc** [comment]
Reliant on work on assessment data collection

**Comment by leebaylis** [comment]
Please resubmit as enhancement using the form and provide context
https://forms.office.com/Pages/ResponsePage.aspx?id=TTn5SBSKJ02CpvNfEjYSBd2sT89nF9RJhClxPe2uce9UNDZVWFlXVUY2TTZZSUxEUFRTSVUzMllDMy4u
