### ISSUE TITLE
VLE Use per Course

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#29]
Request from client site.

**Comment by leebaylis** [comment]
Please resubmit as enhancement using the form and provide context
https://forms.office.com/Pages/ResponsePage.aspx?id=TTn5SBSKJ02CpvNfEjYSBd2sT89nF9RJhClxPe2uce9UNDZVWFlXVUY2TTZZSUxEUFRTSVUzMllDMy4u

**Comment by leebaylis** [comment]
Actually, can this be closed / was it delivered?
