### ISSUE TITLE
Menu accessibility in Chrome

### ISSUE THREAD

**Issue by pjthorman** [jiscdev/data-explorer#34]
When I hover over menus to select a sub menu, when my mouse moves down the menu disappears. Intermittent fault. Happens on OS Windows 7 and the following browsers:

Chrome v 55.0.2883.87 m
IE 11.0.9600.18524

**Comment by michaelwebbjisc** [comment]
I think I've managed to recreate this.  I think it's if you hover over the menu option and then move the move down slowly.  If you do it slowly the menu disappears before you get there, but if you move quicker is doesn't.

**Comment by michaelwebbjisc** [comment]
Fixed  (tested in Chrome)
