### ISSUE TITLE
change year shouldn't take you home

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#51]
It should take you back to where ever you were.

**Comment by robbristow-jisc** [comment]
Is this on Staging or Dev?

**Comment by leebaylis** [comment]
definitely not staging, hopefully it has been rolled to dev :)

**Comment by robbristow-jisc** [comment]
Ok - A couple of points here. 

1. I can change the academic year in the drop down and stay on the same screen (that is, not go home). However what is displayed does not seem not change - I have the same data on screen regardless of which year I am looking at. Is this supposed to change?

2. I note that in the drop down, the year is specifies as 2015 - 2016, for example, Whereas in the breadcrumbs it is just 2015 or 2016, similarly when the little notification pops up it says Academic Year changed to 2015 or 2016, and not the academic year style as in the drop down. Small point, but I found it a little confusing to see which year as I was on.

**Comment by pdiveris** [comment]
Just a quick note to say that a refresh of what you are looking at
should indeed happen. However, I would suggest that this is an entirely
different issue (it's a a series of fixes in all components i.e.
Students Overview, Tutors Overview etc.

**Comment by leebaylis** [comment]
Agreed -- closing this one, and raising two new tickets for Rob's points.
