### ISSUE TITLE
Mouse over data points

### ISSUE THREAD

**Issue by pbailey64** [jiscdev/data-explorer#73]
Make mouse over data points on graphs useful
e.g. assessments - show module code and mark/grade

**Comment by robbristow-jisc** [comment]
I can see mouse over data points on both bar and line graphs. However, all the mouse one points say its "Activity". Might it be possible to make that more meaningful? Like for VLE Activity, can we not make the mouse over say "VLE Access" or VLE Logins or VLE Page Views, or something.

**Comment by robbristow-jisc** [comment]
BTW - Can't see any data at all on Dev this morning - that's v.0.13.6c. The comment above applies to Staging v.0.13.5b

**Comment by michaelwebbjisc** [comment]
This needs to be broken down into specific issues with specific graphs.  I suggest closing this and adding in new issues for each graph with an identified problem.
