### ISSUE TITLE
Add link to Data Explorer Guide

### ISSUE THREAD

**Issue by pbailey64** [jiscdev/data-explorer#76]

**Comment by leebaylis** [comment]
Please resubmit as enhancement using the form and provide context
https://forms.office.com/Pages/ResponsePage.aspx?id=TTn5SBSKJ02CpvNfEjYSBd2sT89nF9RJhClxPe2uce9UNDZVWFlXVUY2TTZZSUxEUFRTSVUzMllDMy4u
