### ISSUE TITLE
DE Feedback

### ISSUE THREAD

**Issue by timstratton** [jiscdev/data-explorer#89]
THORMAN, Phil reported 22 days ago (Tue, 14 Mar at 3:26 PM) via Portal Meta
The UX for the feedback element in DE is a bit confusing:

"I submitted feedback on the system, but the feedback box stays active which could make users think it hasn’t gone and attempt repeated sends."

I've just tested it and note that when you click on the 'Send Feedback' button, it goes blue, but stays blue. Plus the text you have entered doesn't disappear when the acknowledgement arrives. Therefore I can see his point. Screenshot attached from a test in IE, showing 'sent' state.

![de-feedback-ux-sent-state](https://cloud.githubusercontent.com/assets/24383922/24705814/7137acd4-1a05-11e7-9e90-6ce00ea229e9.png)

**Comment by leebaylis** [comment]
Relies on upgraded version in 0.13

**Comment by michaelwebbjisc** [comment]
This feature was removed quite a while ago - it was just a pre-freshdesk tool
