### ISSUE TITLE
Site configuration UI ⚖100+

### ISSUE THREAD

**Issue by pdiveris** [jiscdev/data-explorer#94]
Form for managing the site configuration specifics (see #93)

**Comment by michaelwebbjisc** [comment]
See https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/243 for required area

**Comment by michaelwebbjisc** [comment]
See https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/244 for another area

**Comment by michaelwebbjisc** [comment]
https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/230 another one

**Comment by leebaylis** [comment]
Just running through this with USW, they are confused by the lack of an 'OK' or a 'save' button... even if it is just a link which functionally takes you back to the home screen, can it be added?

**Comment by pdiveris** [comment]
Hey, yes the plan is to add a green/red notifier and a button or something. Will attach a screenshot illustrating what I mean when I get a minute.

**Comment by leebaylis** [comment]
0.12 issues need tying off for testing or moving to 0.12.1, does any of this need rolling over?

**Comment by michaelwebbjisc** [comment]
This really needs completing - I'm going to work with Petros today to get it complete.  It's still a blocker until it's good to go.

**Comment by michaelwebbjisc** [comment]
Place 1:
![image](https://user-images.githubusercontent.com/8233360/28258829-3516d8f8-6acb-11e7-874c-4dca76937fb7.png)

**Comment by michaelwebbjisc** [comment]
![image](https://user-images.githubusercontent.com/8233360/28258838-4266905c-6acb-11e7-9aaa-9389ff777677.png)

**Comment by michaelwebbjisc** [comment]
![image](https://user-images.githubusercontent.com/8233360/28258877-73b17bc2-6acb-11e7-8f4f-67c19f164e16.png)

**Comment by michaelwebbjisc** [comment]
![image](https://user-images.githubusercontent.com/8233360/28258948-d1e66eaa-6acb-11e7-9cd6-16aebad4cdb0.png)

**Comment by michaelwebbjisc** [comment]
![image](https://user-images.githubusercontent.com/8233360/28259001-100e8e24-6acc-11e7-8983-ed73592d52f9.png)

(on student overview)

**Comment by michaelwebbjisc** [comment]
Module overview - attendance graph in this drop down

![image](https://user-images.githubusercontent.com/8233360/28259049-4dc0bd28-6acc-11e7-8384-eabeb684b73c.png)

**Comment by pdiveris** [comment]
Those have been acted upon
See notes for https://bitbucket.org/jiscdigitalfutures/datax-client/commits/61f552d8b13b3a8b8344a7a846d21437877ac113

**Comment by leebaylis** [comment]
I don't think this is working in 0.12 on staging but it is on 0.12.1 on dev. 

What are the implications for making 0.12 live -- do we have to disable this feature in 0.12, or do we have to ditch 0.12 as a release?

**Comment by pdiveris** [comment]
Lee can you help me understand what the issue is with this?

**Comment by leebaylis** [comment]
If you go on staging to UoJ blue, turn on study goal attendence, then go to all tutor, Andrea McDonalid, she has no study goal attendence, and then often when I go back to the config page it has turned itself off again

**Comment by leebaylis** [comment]
But as I say, it's fixed on dev -- so I think we either have to port the code from dev to 0.12 so that we can make 0.12 live, or we have to turn it off somehow

**Comment by pdiveris** [comment]
OK I get you. It is indeed deployed on dev. We'll discuss tomorrow how to move it to 0.12.

**Comment by leebaylis** [comment]
moved to 12.1 which will be made live together with 12
