### ISSUE TITLE
Alphabetise LRW list at login

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#95]
When users with access to more than one LRW log in to the tool, they are presented with a list of LRWs. For higher level admins, this list is not ordered and will only get longer! Can it be alphabetised? Thanks!
<img width="1392" alt="screen shot 2017-05-23 at 11 18 10" src="https://cloud.githubusercontent.com/assets/1846710/26350012/9d1cc6da-3fa9-11e7-9829-f988564892d2.png">

**Comment by leebaylis** [comment]
Michael says this should be a nice easy one to get you started!

**Comment by pdiveris** [comment]
This has been addressed in commit https://bitbucket.org/jiscdigitalfutures/datax-api/commits/ee692a77e92f41ddc2a8c3628730e0bb6a458972

It seems working fine in my dev environment but it needs testing.

**Comment by leebaylis** [comment]
confirmed working in my dev environment on 0.12.1

**Comment by pdiveris** [comment]
X

⁣Sent from BlueMail ​
