### ISSUE TITLE
Meaningless 'Series 1' appears in tooltips

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#96]
e.g. all modules, view one, change viz to VLE content use, hover over a bar.
also appears in Institution > Demographic explorer broken down by socio_ec on the pie chart.

**Comment by pdiveris** [comment]
It is my understand that the label should be either the module's name, which is a repetition since it also sits at the top of the viz, or something like 'Accessed - '. Any comments anyone?

**Comment by leebaylis** [comment]
Where does the series 1 string actually come from?

**Comment by michaelwebbjisc** [comment]
Has this one now been fixed @pdiveris

**Comment by robbristow-jisc** [comment]
What I see now on Dev and Staging is that the tooltip now carries the name of the Content type bar being hovered over. What would make sense to my mind is to have the actual value that the bar represents - on my screen the horizontal axis  and scale is off the bottom of the screen
![screen shot 2017-08-03 at 11 21 14](https://user-images.githubusercontent.com/30286590/28917616-24c71a78-783e-11e7-920a-2d2430778a4b.png)

**Comment by leebaylis** [comment]
I agree, kind of how tableau would do it. I'll raise a new request though so we can mark this one done.
