### ISSUE TITLE
Selecting student, then choosing Activity with Assessments does not show assessments

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/data-explorer#97]
https://jisclearninganalytics.freshdesk.com/helpdesk/tickets/82

or if it does, it doesn't do it for the students I have looked at e.g. USW 00004640 -- it just shows an activity line

**Comment by pdiveris** [comment]
I am discussing with MW exactly what I should be getting there. It appears to me that the flags render twice for some reason. In addition, the time labels at the bottom seem funny (quote symbol, for a start.)

**Comment by pdiveris** [comment]
OK, so we have a a few issues (in order of importance)

- Indicate to the user that nothing is there to see of there is no data
- Fix the duplicate flags issue
- Remove the redundant single quote from the x axis labels

**Comment by leebaylis** [comment]
shall we split into 3 tickets? Or are these all fixable in one block?

**Comment by pdiveris** [comment]
I think it's fine for now as two points are resolved already, but next time we split such tickets..

**Comment by pdiveris** [comment]
I have now released a version on dev and staging which should throw nice yellow popups informing the user that there is no data. I am not sure whether they should be yellow (warning) or blue (info). Also, they are persistent in the sense that they won't ago away after 4 seconds like the other popups do. Please test and advise.

**Comment by leebaylis** [comment]
I would say yellow :)

**Comment by robbristow-jisc** [comment]
I've seen lots of these flags, but I have an issue with them in that they cover the Academic Year pop up, and also I think they ought to go away without being clicked.

**Comment by leebaylis** [comment]
Feedback from user group: Make yellow popups fade after a few seconds rather than need clicking on

**Comment by leebaylis** [comment]
@robbristow-jisc the flags are these: do we confirm there are no longer any duplicates?
<img width="589" alt="screen shot 2017-09-26 at 20 33 37" src="https://user-images.githubusercontent.com/1846710/30880300-06cc3bf2-a2fa-11e7-9e9a-47e657e5efa1.png">

**Comment by robbristow-jisc** [comment]
Can't see any duplicate flags on the Activity with assessment. Agin, just Dev so far Can't see any assessments on USW - are there meant to be any?

**Comment by leebaylis** [comment]
Broken out popup fade to new bug: 
https://github.com/jiscdev/data-explorer/issues/247

**Comment by michaelwebbjisc** [comment]
I've tested this with a know data set and it works as it should, so closing.

![image](https://user-images.githubusercontent.com/8233360/31559051-34c7b69e-b047-11e7-8ac3-22ac5d80c36d.png)
