### ISSUE TITLE
Show results of data aggregations ⚖104

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#98]
Should be at site explorer level

**Comment by pjthorman** [comment]
What's this about? Can't see any details, but note it's in the June sprint.

**Comment by michaelwebbjisc** [comment]
It's the data rolled up at course level rather than module level.  At the moment its vle accesses per course over time.

**Comment by leebaylis** [comment]
0.12 issues need tying off for testing or moving to 0.12.1/0.13, what is the status of this issue?

**Comment by michaelwebbjisc** [comment]
It needs tying off for testing.  It's one of the items that needs to be switch-offable

**Comment by robbristow-jisc** [comment]
No sure what I am looking for here - the details of what is required seem to be missing

**Comment by leebaylis** [comment]
@michaelwebbjisc, in which viz are the data aggregations shown so that Rob can test?

**Comment by robbristow-jisc** [comment]
Still need some guidance here, Lee

**Comment by leebaylis** [comment]
I'll mark it as a blocker

**Comment by leebaylis** [comment]
Unblocked -- @pdiveris had turned the aggregations off, they need turning back on.  Note this graph is only available for Gloucester.

**Comment by leebaylis** [comment]
@pdiveris I just turned on aggregations, but where do they appear? Maybe we need to put that as more info in the config page -- "show aggregations on X screen"

**Comment by leebaylis** [comment]
it's on institution > course overview

**Comment by leebaylis** [comment]
can we add that to the config page -- "show 'institution > course overview' aggregations" or similar

**Comment by robbristow-jisc** [comment]
I am seeing a Course Level Data Table - with a CSV download option button, and many rows of data. See screenshot. One point - it takes a long time to show the data - left me wondering if anything was going to happen
![screen shot 2017-09-19 at 15 43 33](https://user-images.githubusercontent.com/30286590/30598422-92cd4276-9d51-11e7-80ef-75c609ec3bd3.png)

**Comment by leebaylis** [comment]
there's a bug to be picked up by https://github.com/jiscdev/data-explorer/issues/194 and we'll let Rob's observation about loading time be picked up by https://github.com/jiscdev/data-explorer/issues/148; closing this
