### ISSUE TITLE
Blackboard data granularity ⚖80

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#99]
What should our expectations be on the live VLE activity we can show? The bb retention centre shows course activity in quite a granular way;
[see image in freshdesk ticket]
So when data x shows activity this could just mean – “logged in longer than x seconds”. What would be more useful and would develop tel agenda and teaching is a more granular recording of activity.

**Comment by michaelwebbjisc** [comment]
Question rather than dev task

**Comment by leebaylis** [comment]
User Logged In
User Logged out
Course Viewed
Course Content Viewed
Assignment Submitted
Assignment Graded
